Repository Codiary-UMC-6th/Backend-Codiary, pull requests merged in 2024-10, with the labels that each got.

#232 Feat: 마이페이지 정보 조회 API 개발
  src/main/java/com/codiary/backend/domain/member/controller/MemberController.java
  src/main/java/com/codiary/backend/domain/member/converter/MemberConverter.java
  src/main/java/com/codiary/backend/domain/member/dto/response/MemberResponseDTO.java
  src/main/java/com/codiary/backend/domain/member/entity/Member.java
  src/main/java/com/codiary/backend/domain/member/repository/MemberRepository.java
  src/main/java/com/codiary/backend/domain/member/repository/MemberRepositoryCustom.java
  src/main/java/com/codiary/backend/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/com/codiary/backend/domain/member/service/MemberQueryService.java
  src/main/java/com/codiary/backend/domain/team/dto/response/TeamResponseDTO.java
Labels: ✨ Feature

#236 #228 auth 관련 기능 구현
  build.gradle
  src/main/java/com/codiary/backend/domain/member/controller/MemberController.java
  src/main/java/com/codiary/backend/domain/member/dto/request/MemberRequestDTO.java
  src/main/java/com/codiary/backend/domain/member/dto/response/MemberResponseDTO.java
  src/main/java/com/codiary/backend/domain/member/entity/Token.java
  src/main/java/com/codiary/backend/domain/member/repository/TokenRepository.java
  src/main/java/com/codiary/backend/domain/member/scheduler/TokenCleanupScheduler.java
  src/main/java/com/codiary/backend/domain/member/service/MemberCommandService.java
  src/main/java/com/codiary/backend/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/codiary/backend/global/config/RedisConfig.java
  src/main/java/com/codiary/backend/global/config/SecurityConfig.java
  src/main/java/com/codiary/backend/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/codiary/backend/global/jwt/JwtTokenProvider.java
Labels: ✨ Feature

#241 Feat: 팀 생성/프로필 조회 및 수정 API
  src/main/java/com/codiary/backend/domain/member/controller/MemberController.java
  src/main/java/com/codiary/backend/domain/member/converter/MemberConverter.java
  src/main/java/com/codiary/backend/domain/member/dto/request/MemberRequestDTO.java
  src/main/java/com/codiary/backend/domain/member/dto/response/MemberResponseDTO.java
  src/main/java/com/codiary/backend/domain/member/entity/Member.java
  src/main/java/com/codiary/backend/domain/member/repository/MemberRepositoryCustom.java
  src/main/java/com/codiary/backend/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/com/codiary/backend/domain/member/service/MemberCommandService.java
  src/main/java/com/codiary/backend/domain/member/service/MemberQueryService.java
  src/main/java/com/codiary/backend/domain/team/controller/TeamController.java
  src/main/java/com/codiary/backend/domain/team/converter/TeamConverter.java
  src/main/java/com/codiary/backend/domain/team/dto/request/TeamRequestDTO.java
  src/main/java/com/codiary/backend/domain/team/dto/response/TeamResponseDTO.java
  src/main/java/com/codiary/backend/domain/team/entity/Team.java
  src/main/java/com/codiary/backend/domain/team/entity/TeamMember.java
  src/main/java/com/codiary/backend/domain/team/enumerate/TeamMemberRole.java
  src/main/java/com/codiary/backend/domain/team/repository/TeamRepository.java
  src/main/java/com/codiary/backend/domain/team/repository/TeamRepositoryCustom.java
  src/main/java/com/codiary/backend/domain/team/repository/TeamRepositoryImpl.java
  src/main/java/com/codiary/backend/domain/team/service/TeamService.java
  src/main/java/com/codiary/backend/domain/techstack/entity/TechStacks.java
  src/main/java/com/codiary/backend/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ Feature

#237 Feat: 사용자 정보 조회/수정 API
  src/main/java/com/codiary/backend/domain/member/dto/response/MemberResponseDTO.java
Labels: ✨ Feature

#242 Fix: MemberInfoDTO 삭제
  src/main/java/com/codiary/backend/domain/member/dto/response/MemberResponseDTO.java
Labels: 🎀 Fix

#244 Feat: 팀 팔로우 관련 기능 구현
  src/main/java/com/codiary/backend/domain/member/repository/MemberRepositoryCustom.java
  src/main/java/com/codiary/backend/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/com/codiary/backend/domain/team/controller/TeamFollowController.java
  src/main/java/com/codiary/backend/domain/team/converter/TeamConverter.java
  src/main/java/com/codiary/backend/domain/team/dto/response/TeamResponseDTO.java
  src/main/java/com/codiary/backend/domain/team/entity/TeamFollow.java
  src/main/java/com/codiary/backend/domain/team/repository/TeamFollowRepository.java
  src/main/java/com/codiary/backend/domain/team/repository/TeamFollowRepositoryCustom.java
  src/main/java/com/codiary/backend/domain/team/repository/TeamFollowRepositoryImpl.java
  src/main/java/com/codiary/backend/domain/team/repository/TeamRepositoryCustom.java
  src/main/java/com/codiary/backend/domain/team/repository/TeamRepositoryImpl.java
  src/main/java/com/codiary/backend/domain/team/service/TeamFollowService.java
  src/main/java/com/codiary/backend/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/codiary/backend/global/apiPayload/exception/handler/TeamHandler.java
Labels: ✨ Feature

#245 Refactor: auth 관련 코드 member에서 분리 & @AuthenticationPrincipal을 이용하여 요청자 정보 조회 가능하게 기능 구현
  src/main/java/com/codiary/backend/domain/member/controller/AuthController.java
  src/main/java/com/codiary/backend/domain/member/controller/MemberController.java
  src/main/java/com/codiary/backend/domain/member/converter/MemberConverter.java
  src/main/java/com/codiary/backend/domain/member/dto/request/MemberRequestDTO.java
  src/main/java/com/codiary/backend/domain/member/entity/Member.java
  src/main/java/com/codiary/backend/domain/member/security/CustomMemberDetails.java
  src/main/java/com/codiary/backend/domain/member/security/CustomMemberDetailsService.java
  src/main/java/com/codiary/backend/domain/member/service/AuthService.java
  src/main/java/com/codiary/backend/domain/member/service/MemberCommandService.java
  src/main/java/com/codiary/backend/domain/member/service/SocialLoginService.java
  src/main/java/com/codiary/backend/global/config/SecurityConfig.java
  src/main/java/com/codiary/backend/global/jwt/JwtTokenProvider.java
Labels: 🔨 Refactor

#247 Feat: Full-text Search를 이용한 다이어리 검색 결과 페이지네이션
  .github/workflows/cicd.yml
  src/main/java/com/codiary/backend/domain/post/controller/PostController.java
  src/main/java/com/codiary/backend/domain/post/converter/PostConverter.java
  src/main/java/com/codiary/backend/domain/post/dto/response/PostResponseDTO.java
  src/main/java/com/codiary/backend/domain/post/repository/PostRepository.java
  src/main/java/com/codiary/backend/domain/post/repository/PostRepositoryCustom.java
  src/main/java/com/codiary/backend/domain/post/repository/PostRepositoryImpl.java
  src/main/java/com/codiary/backend/domain/post/service/PostService.java
  src/main/java/com/codiary/backend/global/config/CustomFunctionContributor.java
  src/main/java/com/codiary/backend/global/config/SecurityConfig.java
  src/main/resources/META-INF/services/org.hibernate.boot.model.FunctionContributor
Labels: ✨ Feature

#249 Feat: 팀원 추가/삭제/조회 API 개발
  src/main/java/com/codiary/backend/domain/member/converter/MemberConverter.java
  src/main/java/com/codiary/backend/domain/member/repository/MemberRepository.java
  src/main/java/com/codiary/backend/domain/team/controller/TeamController.java
  src/main/java/com/codiary/backend/domain/team/converter/TeamConverter.java
  src/main/java/com/codiary/backend/domain/team/dto/request/TeamRequestDTO.java
  src/main/java/com/codiary/backend/domain/team/dto/response/TeamResponseDTO.java
  src/main/java/com/codiary/backend/domain/team/entity/TeamMember.java
  src/main/java/com/codiary/backend/domain/team/repository/TeamFollowRepository.java
  src/main/java/com/codiary/backend/domain/team/repository/TeamMemberRepository.java
  src/main/java/com/codiary/backend/domain/team/repository/TeamRepositoryCustom.java
  src/main/java/com/codiary/backend/domain/team/repository/TeamRepositoryImpl.java
  src/main/java/com/codiary/backend/domain/team/service/TeamFollowService.java
  src/main/java/com/codiary/backend/domain/team/service/TeamMemberService.java
  src/main/java/com/codiary/backend/domain/team/service/TeamService.java
  src/main/java/com/codiary/backend/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/codiary/backend/global/config/SecurityConfig.java
Labels: ✨ Feature
