Repository Codiary-UMC-6th/Backend-Codiary, pull requests merged in 2024-11, with the labels that each got.

#255 Feat: 소셜 로그인 마이그레이션
  src/main/java/com/codiary/backend/domain/member/controller/SocialLoginController.java
  src/main/java/com/codiary/backend/domain/member/repository/MemberRepository.java
  src/main/java/com/codiary/backend/domain/member/service/SocialLoginService.java
  src/main/java/com/codiary/backend/global/config/SecurityConfig.java
  src/main/java/com/codiary/backend/global/jwt/JwtTokenProvider.java
Labels: ✨ Feature

#254 Feat: 회원별 카테고리 생성/조회/삭제
  src/main/java/com/codiary/backend/domain/category/controller/CategoryController.java
  src/main/java/com/codiary/backend/domain/category/converter/CategoryConverter.java
  src/main/java/com/codiary/backend/domain/category/dto/CategoryResponseDTO.java
  src/main/java/com/codiary/backend/domain/category/entity/Category.java
  src/main/java/com/codiary/backend/domain/category/repository/CategoryRepository.java
  src/main/java/com/codiary/backend/domain/category/service/CategoryService.java
  src/main/java/com/codiary/backend/domain/member/entity/MemberCategory.java
  src/main/java/com/codiary/backend/domain/member/repository/MemberCategoryRepository.java
  src/main/java/com/codiary/backend/domain/member/repository/MemberRepositoryCustom.java
  src/main/java/com/codiary/backend/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/com/codiary/backend/domain/post/entity/Post.java
  src/main/java/com/codiary/backend/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ Feature

#261 Fix: CORS 설정
  src/main/java/com/codiary/backend/domain/post/controller/PostController.java
  src/main/java/com/codiary/backend/domain/post/converter/PostConverter.java
  src/main/java/com/codiary/backend/domain/post/converter/PostFileConverter.java
  src/main/java/com/codiary/backend/domain/post/dto/request/PostRequestDTO.java
  src/main/java/com/codiary/backend/domain/post/dto/response/PostFileResponseDTO.java
  src/main/java/com/codiary/backend/domain/post/dto/response/PostResponseDTO.java
  src/main/java/com/codiary/backend/domain/post/entity/Post.java
  src/main/java/com/codiary/backend/domain/post/entity/PostFile.java
  src/main/java/com/codiary/backend/domain/post/repository/PostFileRepository.java
  src/main/java/com/codiary/backend/domain/post/service/PostCommandService.java
  src/main/java/com/codiary/backend/domain/post/service/PostQueryService.java
  src/main/java/com/codiary/backend/domain/project/repository/ProjectRepository.java
  src/main/java/com/codiary/backend/global/config/RedisConfig.java
  src/main/java/com/codiary/backend/global/config/SecurityConfig.java
Labels: 🌏 Deploy

#253 Feat: team image
  src/main/java/com/codiary/backend/domain/member/entity/Uuid.java
  src/main/java/com/codiary/backend/domain/member/service/MemberCommandService.java
  src/main/java/com/codiary/backend/domain/team/controller/TeamController.java
  src/main/java/com/codiary/backend/domain/team/converter/TeamConverter.java
  src/main/java/com/codiary/backend/domain/team/dto/request/TeamRequestDTO.java
  src/main/java/com/codiary/backend/domain/team/dto/response/TeamResponseDTO.java
  src/main/java/com/codiary/backend/domain/team/entity/Team.java
  src/main/java/com/codiary/backend/domain/team/entity/TeamBannerImage.java
  src/main/java/com/codiary/backend/domain/team/entity/TeamProfileImage.java
  src/main/java/com/codiary/backend/domain/team/repository/TeamBannerImageRepository.java
  src/main/java/com/codiary/backend/domain/team/repository/TeamProfileImageRepository.java
  src/main/java/com/codiary/backend/domain/team/service/TeamService.java
  src/main/java/com/codiary/backend/global/common/uuid/Uuid.java
  src/main/java/com/codiary/backend/global/common/uuid/UuidRepository.java
  src/main/java/com/codiary/backend/global/config/SecurityConfig.java
  src/main/java/com/codiary/backend/global/s3/AmazonS3Manager.java
Labels: ✨ Feature

#260 Feat: 게시글 생성, 수정, 삭제 API 기능 구현
  src/main/java/com/codiary/backend/domain/post/controller/PostController.java
  src/main/java/com/codiary/backend/domain/post/converter/PostConverter.java
  src/main/java/com/codiary/backend/domain/post/dto/request/PostRequestDTO.java
  src/main/java/com/codiary/backend/domain/post/dto/response/PostResponseDTO.java
  src/main/java/com/codiary/backend/domain/post/entity/Post.java
  src/main/java/com/codiary/backend/domain/post/service/PostCommandService.java
Labels: ✨ Feature

#266 Refactor: Uuid entity, repository 관련 오류 수정
  src/main/java/com/codiary/backend/domain/post/service/PostCommandService.java
Labels: 🔨 Refactor

#257 Feat: 게시물 댓글 CRUD 구현
  src/main/java/com/codiary/backend/domain/comment/controller/CommentController.java
  src/main/java/com/codiary/backend/domain/comment/converter/CommentConverter.java
  src/main/java/com/codiary/backend/domain/comment/dto/request/CommentRequestDTO.java
  src/main/java/com/codiary/backend/domain/comment/dto/response/CommentResponseDTO.java
  src/main/java/com/codiary/backend/domain/comment/entity/Comment.java
  src/main/java/com/codiary/backend/domain/comment/repository/CommentRepository.java
  src/main/java/com/codiary/backend/domain/comment/repository/CommentRepositoryCustom.java
  src/main/java/com/codiary/backend/domain/comment/repository/CommentRepositoryImpl.java
  src/main/java/com/codiary/backend/domain/comment/service/CommentService.java
  src/main/java/com/codiary/backend/domain/post/service/PostCommandService.java
  src/main/java/com/codiary/backend/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ Feature

#267 Feat: 댓글 페이징 구현
  src/main/java/com/codiary/backend/domain/comment/controller/CommentController.java
  src/main/java/com/codiary/backend/domain/comment/repository/CommentRepositoryCustom.java
  src/main/java/com/codiary/backend/domain/comment/repository/CommentRepositoryImpl.java
  src/main/java/com/codiary/backend/domain/comment/service/CommentService.java
Labels: ✨ Feature

#268 Feat: 멤버 이미지, 포지션 추가 반환
  src/main/java/com/codiary/backend/domain/member/controller/MemberController.java
  src/main/java/com/codiary/backend/domain/member/converter/MemberConverter.java
  src/main/java/com/codiary/backend/domain/member/dto/response/MemberResponseDTO.java
  src/main/java/com/codiary/backend/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/com/codiary/backend/domain/team/converter/TeamConverter.java
  src/main/java/com/codiary/backend/domain/team/dto/request/TeamRequestDTO.java
  src/main/java/com/codiary/backend/domain/team/dto/response/TeamResponseDTO.java
  src/main/java/com/codiary/backend/domain/team/entity/TeamMember.java
  src/main/java/com/codiary/backend/domain/team/service/TeamService.java
Labels: ✨ Feature

#269 Feat: 저자의 다이어리 리스트 페이징 조회 API 기능 구현
  src/main/java/com/codiary/backend/domain/post/controller/PostController.java
  src/main/java/com/codiary/backend/domain/post/converter/PostConverter.java
  src/main/java/com/codiary/backend/domain/post/dto/response/PostResponseDTO.java
  src/main/java/com/codiary/backend/domain/post/repository/PostRepository.java
  src/main/java/com/codiary/backend/domain/post/service/PostQueryService.java
  src/main/java/com/codiary/backend/domain/team/repository/TeamRepository.java
  src/main/java/com/codiary/backend/global/config/SecurityConfig.java
Labels: ✨ Feature

#270 Refactor: Endpoint 복수형으로 되어있는 부분 단수형으로 변경
  src/main/java/com/codiary/backend/global/config/RedisConfig.java
  src/main/java/com/codiary/backend/global/config/SecurityConfig.java
Labels: 🔨 Refactor

#271 Feat: 게시글 조회 관련 API 기능 개발
  src/main/java/com/codiary/backend/domain/category/service/CategoryService.java
  src/main/java/com/codiary/backend/domain/member/controller/AuthController.java
  src/main/java/com/codiary/backend/domain/member/controller/FollowController.java
  src/main/java/com/codiary/backend/domain/member/controller/MemberController.java
  src/main/java/com/codiary/backend/domain/post/controller/PostController.java
  src/main/java/com/codiary/backend/domain/post/converter/PostConverter.java
  src/main/java/com/codiary/backend/domain/post/dto/response/PostResponseDTO.java
  src/main/java/com/codiary/backend/domain/post/entity/Post.java
  src/main/java/com/codiary/backend/domain/post/repository/PostRepository.java
  src/main/java/com/codiary/backend/domain/post/service/PostCommandService.java
  src/main/java/com/codiary/backend/domain/post/service/PostQueryService.java
  src/main/java/com/codiary/backend/domain/team/controller/TeamController.java
  src/main/java/com/codiary/backend/domain/team/controller/TeamFollowController.java
Labels: ✨ Feature

#273 Feat: 대댓글 CRUD 구현
  src/main/java/com/codiary/backend/domain/comment/controller/CommentController.java
  src/main/java/com/codiary/backend/domain/comment/converter/CommentConverter.java
  src/main/java/com/codiary/backend/domain/comment/dto/response/CommentResponseDTO.java
  src/main/java/com/codiary/backend/domain/comment/entity/Comment.java
  src/main/java/com/codiary/backend/domain/comment/repository/CommentRepositoryCustom.java
  src/main/java/com/codiary/backend/domain/comment/repository/CommentRepositoryImpl.java
  src/main/java/com/codiary/backend/domain/comment/service/CommentService.java
  src/main/java/com/codiary/backend/global/config/SecurityConfig.java
Labels: ✨ Feature

#272 Feat: 캘린더 조회 API
  src/main/java/com/codiary/backend/domain/member/controller/MemberController.java
  src/main/java/com/codiary/backend/domain/member/converter/MemberConverter.java
  src/main/java/com/codiary/backend/domain/member/dto/response/MemberResponseDTO.java
  src/main/java/com/codiary/backend/domain/member/service/MemberQueryService.java
  src/main/java/com/codiary/backend/domain/post/dto/response/PostResponseDTO.java
  src/main/java/com/codiary/backend/domain/post/repository/PostRepositoryCustom.java
  src/main/java/com/codiary/backend/domain/post/repository/PostRepositoryImpl.java
  src/main/java/com/codiary/backend/domain/project/dto/response/ProjectResponseDTO.java
  src/main/java/com/codiary/backend/domain/project/repository/ProjectRepository.java
  src/main/java/com/codiary/backend/domain/project/repository/ProjectRepositoryCustom.java
  src/main/java/com/codiary/backend/domain/project/repository/ProjectRepositoryImpl.java
Labels: ✨ Feature

#277 Feat: bookmark 관련 코드 구현
  src/main/java/com/codiary/backend/domain/post/controller/PostController.java
  src/main/java/com/codiary/backend/domain/post/converter/PostConverter.java
  src/main/java/com/codiary/backend/domain/post/dto/response/PostResponseDTO.java
  src/main/java/com/codiary/backend/domain/post/entity/Bookmark.java
  src/main/java/com/codiary/backend/domain/post/repository/BookmarkRepository.java
  src/main/java/com/codiary/backend/domain/post/service/BookmarkService.java
  src/main/java/com/codiary/backend/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ Feature

#275 Feat: 인기순, 최신순 post 조회
  src/main/java/com/codiary/backend/domain/member/entity/Member.java
  src/main/java/com/codiary/backend/domain/post/controller/PostController.java
  src/main/java/com/codiary/backend/domain/post/converter/PostConverter.java
  src/main/java/com/codiary/backend/domain/post/dto/response/PostResponseDTO.java
  src/main/java/com/codiary/backend/domain/post/repository/PostRepositoryCustom.java
  src/main/java/com/codiary/backend/domain/post/repository/PostRepositoryImpl.java
  src/main/java/com/codiary/backend/domain/post/service/PostService.java
  src/main/java/com/codiary/backend/global/config/SecurityConfig.java
Labels: ✨ Feature

#279 Feat: 개인/팀 프로젝트 생성 및 조회
  src/main/java/com/codiary/backend/domain/member/converter/MemberConverter.java
  src/main/java/com/codiary/backend/domain/member/entity/Member.java
  src/main/java/com/codiary/backend/domain/member/entity/MemberProjectMap.java
  src/main/java/com/codiary/backend/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/com/codiary/backend/domain/project/controller/ProjectController.java
  src/main/java/com/codiary/backend/domain/project/converter/ProjectConverter.java
  src/main/java/com/codiary/backend/domain/project/dto/response/ProjectResponseDTO.java
  src/main/java/com/codiary/backend/domain/project/entity/Project.java
  src/main/java/com/codiary/backend/domain/project/repository/ProjectRepository.java
  src/main/java/com/codiary/backend/domain/project/repository/ProjectRepositoryCustom.java
  src/main/java/com/codiary/backend/domain/project/repository/ProjectRepositoryImpl.java
  src/main/java/com/codiary/backend/domain/project/service/ProjectService.java
  src/main/java/com/codiary/backend/domain/team/converter/TeamConverter.java
  src/main/java/com/codiary/backend/domain/team/entity/Team.java
  src/main/java/com/codiary/backend/domain/team/entity/TeamProjectMap.java
Labels: ✨ Feature

#281 Feat: 북마크한 게시글 목록 조회 API
  src/main/java/com/codiary/backend/domain/post/controller/PostController.java
  src/main/java/com/codiary/backend/domain/post/converter/PostConverter.java
  src/main/java/com/codiary/backend/domain/post/dto/response/PostResponseDTO.java
  src/main/java/com/codiary/backend/domain/post/repository/PostRepositoryCustom.java
  src/main/java/com/codiary/backend/domain/post/repository/PostRepositoryImpl.java
  src/main/java/com/codiary/backend/domain/post/service/PostQueryService.java
Labels: ✨ Feature

#285 Feat: search post
  src/main/java/com/codiary/backend/domain/post/controller/PostController.java
  src/main/java/com/codiary/backend/domain/post/repository/PostRepositoryCustom.java
  src/main/java/com/codiary/backend/domain/post/repository/PostRepositoryImpl.java
  src/main/java/com/codiary/backend/domain/post/service/PostService.java
Labels: ✨ Feature
