Repository Codiary-UMC-6th/Backend-Codiary, pull requests merged in 2024-08, with the labels that each got.

#68 #59 Feat: 회원별 관심 카테고리 기능
  src/main/java/com/codiary/backend/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/codiary/backend/global/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/codiary/backend/global/converter/MemberCategoryConverter.java
  src/main/java/com/codiary/backend/global/converter/MemberConverter.java
  src/main/java/com/codiary/backend/global/domain/entity/Member.java
  src/main/java/com/codiary/backend/global/domain/entity/mapping/Categories.java
  src/main/java/com/codiary/backend/global/domain/entity/mapping/MemberCategory.java
  src/main/java/com/codiary/backend/global/repository/MemberCategoryRepository.java
  src/main/java/com/codiary/backend/global/service/CategoryService/CategoryCommandService.java
  src/main/java/com/codiary/backend/global/service/CategoryService/CategoryCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/service/MemberCategoryService/MemberCategoryCommandService.java
  src/main/java/com/codiary/backend/global/service/MemberCategoryService/MemberCategoryCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/service/MemberService/MemberCommandService.java
  src/main/java/com/codiary/backend/global/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/service/MemberService/MemberQueryService.java
  src/main/java/com/codiary/backend/global/service/MemberService/MemberQueryServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/BookmarkController.java
  src/main/java/com/codiary/backend/global/web/controller/CategoryController.java
  src/main/java/com/codiary/backend/global/web/controller/MemberCategoryController.java
  src/main/java/com/codiary/backend/global/web/controller/MemberController.java
  src/main/java/com/codiary/backend/global/web/dto/Category/CategoryResponseDTO.java
  src/main/java/com/codiary/backend/global/web/dto/Member/MemberResponseDTO.java
  src/main/java/com/codiary/backend/global/web/dto/MemberCategory/MemberCategoryRequestDTO.java
  src/main/java/com/codiary/backend/global/web/dto/MemberCategory/MemberCategoryResponseDTO.java
Labels: ✨ Feature

#70 Feature/#52 user profile image
  src/main/java/com/codiary/backend/global/domain/entity/Member.java
  src/main/java/com/codiary/backend/global/domain/entity/MemberImage.java
  src/main/java/com/codiary/backend/global/repository/MemberImageRepository.java
  src/main/java/com/codiary/backend/global/service/MemberService/MemberCommandService.java
  src/main/java/com/codiary/backend/global/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/MemberController.java
  src/main/java/com/codiary/backend/global/web/dto/Member/MemberRequestDTO.java
  src/main/java/com/codiary/backend/global/web/dto/Member/MemberResponseDTO.java
Labels: ✨ Feature

#72 Refactor: Post 리스트 조회시 다이어리 글에 포함된 이미지 url도 함께 반환하도록 수정
  src/main/java/com/codiary/backend/global/converter/PostConverter.java
  src/main/java/com/codiary/backend/global/web/dto/Post/PostResponseDTO.java
Labels: 🔨 Refactor

#76 Feat: 카테고리별 내 다이어리 목록 조회
  src/main/java/com/codiary/backend/global/repository/PostRepository.java
  src/main/java/com/codiary/backend/global/service/MemberService/MemberQueryService.java
  src/main/java/com/codiary/backend/global/service/MemberService/MemberQueryServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/MemberController.java
Labels: ✨ Feature

#77 Feature/#43 team crud create
  src/main/java/com/codiary/backend/global/converter/TeamConverter.java
  src/main/java/com/codiary/backend/global/service/TeamService/TeamCommandService.java
  src/main/java/com/codiary/backend/global/web/controller/TeamController.java
  src/main/java/com/codiary/backend/global/web/dto/Team/TeamRequestDTO.java
  src/main/java/com/codiary/backend/global/web/dto/Team/TeamResponseDTO.java
  src/main/java/com/codiary/backend/global/web/dto/TeamMember/TeamMemberResponseDTO.java
Labels: ✨ Feature

#80 Feature/#78 profile update
  src/main/java/com/codiary/backend/global/service/TeamService/TeamCommandService.java
  src/main/java/com/codiary/backend/global/web/controller/TeamController.java
  src/main/java/com/codiary/backend/global/web/dto/Team/TeamResponseDTO.java
  src/main/java/com/codiary/backend/global/web/dto/TeamMember/TeamMemberRequestDTO.java
Labels: ✨ Feature

#90 #89 Fix: 팀 controller 주석처리 취소
  src/main/java/com/codiary/backend/global/web/controller/TeamController.java
Labels: 🎀 Fix

#93 Feat: Techstack 추가 기능 개발
  src/main/java/com/codiary/backend/global/config/WebConfig.java
  src/main/java/com/codiary/backend/global/converter/MemberConverter.java
  src/main/java/com/codiary/backend/global/domain/entity/mapping/TechStacks.java
  src/main/java/com/codiary/backend/global/domain/enums/TechStack.java
  src/main/java/com/codiary/backend/global/repository/MemberRepository.java
  src/main/java/com/codiary/backend/global/service/MemberService/MemberCommandService.java
  src/main/java/com/codiary/backend/global/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/MemberController.java
  src/main/java/com/codiary/backend/global/web/dto/Member/MemberResponseDTO.java
Labels: ✨ Feature

#95 Feat:마이페이지 프로젝트 추가 기능 개발
  src/main/java/com/codiary/backend/global/converter/MemberConverter.java
  src/main/java/com/codiary/backend/global/domain/entity/Project.java
  src/main/java/com/codiary/backend/global/domain/entity/mapping/MemberProjectMap.java
  src/main/java/com/codiary/backend/global/repository/MemberProjectMapRepository.java
  src/main/java/com/codiary/backend/global/repository/MemberRepository.java
  src/main/java/com/codiary/backend/global/service/MemberService/FollowService.java
  src/main/java/com/codiary/backend/global/service/MemberService/MemberCommandService.java
  src/main/java/com/codiary/backend/global/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/service/MemberService/MemberQueryService.java
  src/main/java/com/codiary/backend/global/service/MemberService/MemberQueryServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/MemberController.java
  src/main/java/com/codiary/backend/global/web/dto/Member/MemberResponseDTO.java
Labels: ✨ Feature

#96 Feat: 사용자 정보 조회 및 수정 기능 개발
  src/main/java/com/codiary/backend/global/converter/MemberConverter.java
  src/main/java/com/codiary/backend/global/domain/entity/Member.java
  src/main/java/com/codiary/backend/global/service/MemberService/MemberCommandService.java
  src/main/java/com/codiary/backend/global/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/MemberController.java
  src/main/java/com/codiary/backend/global/web/dto/Member/MemberRequestDTO.java
  src/main/java/com/codiary/backend/global/web/dto/Member/MemberResponseDTO.java
Labels: ✨ Feature

#97 Feat: 다이어리 관련 Api 멤버 토큰으로 접근 권한 설정
  src/main/java/com/codiary/backend/global/config/SecurityConfig.java
  src/main/java/com/codiary/backend/global/config/SwaggerConfig.java
  src/main/java/com/codiary/backend/global/domain/entity/Post.java
  src/main/java/com/codiary/backend/global/jwt/EmailPasswordAuthenticationFilter.java
  src/main/java/com/codiary/backend/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/codiary/backend/global/jwt/JwtTokenProvider.java
  src/main/java/com/codiary/backend/global/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/service/PostService/PostCommandService.java
  src/main/java/com/codiary/backend/global/service/PostService/PostCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/service/PostService/PostQueryService.java
  src/main/java/com/codiary/backend/global/service/PostService/PostQueryServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/PostController.java
Labels: ✨ Feature, 🔨 Refactor

#98 Feat: 다이어리 관련 Api 멤버 토큰으로 접근 권한 설정
  src/main/java/com/codiary/backend/global/jwt/JwtAuthenticationFilter.java
Labels: ✨ Feature, 🔨 Refactor

#99 Refactor: Post 컨트롤러 주석 오타 수정
  src/main/java/com/codiary/backend/global/web/controller/PostController.java
Labels: 🔨 Refactor

#102 Feature/#91 teammember add delete
  src/main/java/com/codiary/backend/global/converter/TeamConverter.java
  src/main/java/com/codiary/backend/global/converter/TeamMemberConverter.java
  src/main/java/com/codiary/backend/global/domain/entity/mapping/TeamMember.java
  src/main/java/com/codiary/backend/global/repository/TeamMemberRepository.java
  src/main/java/com/codiary/backend/global/service/TeamMemberService/TeamMemberCommandService.java
  src/main/java/com/codiary/backend/global/service/TeamMemberService/TeamMemberCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/service/TeamService/TeamQueryService.java
  src/main/java/com/codiary/backend/global/service/TeamService/TeamQueryServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/TeamController.java
  src/main/java/com/codiary/backend/global/web/controller/TeamMemberController.java
  src/main/java/com/codiary/backend/global/web/dto/Team/TeamResponseDTO.java
  src/main/java/com/codiary/backend/global/web/dto/TeamMember/TeamMemberRequestDTO.java
  src/main/java/com/codiary/backend/global/web/dto/TeamMember/TeamMemberResponseDTO.java
Labels: ✨ Feature

#104 Feat: 팀 관련 이미지 저장 기능
  src/main/java/com/codiary/backend/global/config/S3Config.java
  src/main/java/com/codiary/backend/global/converter/TeamConverter.java
  src/main/java/com/codiary/backend/global/domain/entity/Team.java
  src/main/java/com/codiary/backend/global/domain/entity/TeamBannerImage.java
  src/main/java/com/codiary/backend/global/domain/entity/TeamProfileImage.java
  src/main/java/com/codiary/backend/global/repository/TeamBannerImageRepository.java
  src/main/java/com/codiary/backend/global/repository/TeamProfileImageRepository.java
  src/main/java/com/codiary/backend/global/s3/AmazonS3Manager.java
  src/main/java/com/codiary/backend/global/service/TeamService/TeamCommandService.java
  src/main/java/com/codiary/backend/global/service/TeamService/TeamCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/service/TeamService/TeamQueryService.java
  src/main/java/com/codiary/backend/global/service/TeamService/TeamQueryServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/TeamController.java
  src/main/java/com/codiary/backend/global/web/dto/Team/TeamRequestDTO.java
  src/main/java/com/codiary/backend/global/web/dto/Team/TeamResponseDTO.java
Labels: ✨ Feature

#107 Feat: 포스트 수정 시 이미지 추가 가능하게 구현
  src/main/java/com/codiary/backend/global/service/PostService/PostCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/PostController.java
  src/main/java/com/codiary/backend/global/web/dto/Post/PostRequestDTO.java
Labels: ✨ Feature

#109 Feat: 마이페이지 team 조회 기능
  src/main/java/com/codiary/backend/global/domain/enums/MemberRole.java
  src/main/java/com/codiary/backend/global/repository/MemberRepository.java
  src/main/java/com/codiary/backend/global/service/MemberService/MemberQueryServiceImpl.java
Labels: ✨ Feature

#110 Retactor & Feat: 팀 이미지 관련 CRUD 수정
  src/main/java/com/codiary/backend/global/converter/TeamConverter.java
  src/main/java/com/codiary/backend/global/service/TeamService/TeamCommandService.java
  src/main/java/com/codiary/backend/global/service/TeamService/TeamCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/service/TeamService/TeamQueryServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/TeamController.java
  src/main/java/com/codiary/backend/global/web/dto/Team/TeamRequestDTO.java
Labels: ✨ Feature, 🔨 Refactor

#113 Refactor: 다이어리 조회 기능 Api 멤버 토큰 인증 방식 변경 및 memberId RequestParam으로 필요한 기능은 다시 추가
  src/main/java/com/codiary/backend/global/config/SecurityConfig.java
  src/main/java/com/codiary/backend/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/codiary/backend/global/service/PostService/PostQueryService.java
  src/main/java/com/codiary/backend/global/service/PostService/PostQueryServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/PostController.java
Labels: 🔨 Refactor

#114 Fix: 내가 쓴 글 프로젝트별로 조회 보류
  src/main/java/com/codiary/backend/global/config/SecurityConfig.java
  src/main/java/com/codiary/backend/global/repository/PostRepository.java
  src/main/java/com/codiary/backend/global/service/MemberService/MemberQueryService.java
  src/main/java/com/codiary/backend/global/service/MemberService/MemberQueryServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/MemberController.java
Labels: 🎀 Fix

#117 Refactor: 저자의 다이어리 조회시 공동저자 설정된 다이어리도 조회하도록 기능 수정
  src/main/java/com/codiary/backend/global/repository/PostRepository.java
  src/main/java/com/codiary/backend/global/service/PostService/PostQueryServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/PostController.java
Labels: 🔨 Refactor

#118 Feat: Profile 닉네임 반환 추가
  src/main/java/com/codiary/backend/global/converter/MemberConverter.java
  src/main/java/com/codiary/backend/global/web/dto/Member/MemberResponseDTO.java
Labels: 📬 API

#120 Fix: authorsList 관련 JPA 사용 오류 fix
  src/main/java/com/codiary/backend/global/service/PostService/PostQueryServiceImpl.java
Labels: 🎀 Fix

#121 Fix: Post entity 수정
  src/main/java/com/codiary/backend/global/domain/entity/Post.java
  src/main/java/com/codiary/backend/global/service/PostService/PostQueryServiceImpl.java
Labels: 🎀 Fix

#122 Feat: post 대표 이미지 설정 기능 구현
  src/main/java/com/codiary/backend/global/converter/MemberConverter.java
  src/main/java/com/codiary/backend/global/converter/PostConverter.java
  src/main/java/com/codiary/backend/global/domain/entity/Post.java
  src/main/java/com/codiary/backend/global/service/PostService/PostCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/web/dto/Member/MemberResponseDTO.java
  src/main/java/com/codiary/backend/global/web/dto/Post/PostRequestDTO.java
  src/main/java/com/codiary/backend/global/web/dto/Post/PostResponseDTO.java
Labels: ✨ Feature

#123 Fix: Post entity fix
  src/main/java/com/codiary/backend/global/domain/entity/Post.java
Labels: 🎀 Fix

#124 Fix: Post entity fix
  src/main/java/com/codiary/backend/global/domain/entity/Post.java
Labels: 🎀 Fix

#126 Feat & Refactor: 회원가입 수정
  src/main/java/com/codiary/backend/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/codiary/backend/global/config/SecurityConfig.java
  src/main/java/com/codiary/backend/global/repository/MemberRepository.java
  src/main/java/com/codiary/backend/global/service/MemberService/MemberCommandService.java
  src/main/java/com/codiary/backend/global/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/MemberController.java
  src/main/java/com/codiary/backend/global/web/dto/Member/MemberRequestDTO.java
Labels: ✨ Feature, 🔨 Refactor

#127 Fix: 다이어리 조회시 teamId 또는 projectId 값이 null이어도 정상 조회되도록 postConverter 수정
  src/main/java/com/codiary/backend/global/converter/PostConverter.java
  src/main/java/com/codiary/backend/global/service/PostService/PostQueryServiceImpl.java
Labels: 🎀 Fix

#128 Fix : 다이어리 생성시 teamId, projectId를 입력하더라도 null값으로 저장되는 오류 수정
  src/main/java/com/codiary/backend/global/converter/PostConverter.java
  src/main/java/com/codiary/backend/global/domain/entity/Post.java
  src/main/java/com/codiary/backend/global/service/PostService/PostCommandService.java
  src/main/java/com/codiary/backend/global/service/PostService/PostCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/PostController.java
Labels: 🎀 Fix

#130 Refactor: 공동저자로 되어있는 다이어리를 포함하여 저자의 다이어리 조회할때 첫페이지에 5개씩 반환 안되던 오류 수정
  src/main/java/com/codiary/backend/global/service/PostService/PostQueryServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/PostController.java
Labels: 🔨 Refactor

#131 Refactor: 프로젝트별 저자의 다이어리 페이징 조회, 팀별 저자의 다이어리 페이징 조회 기능에서도 공동저자로 설정된 다이어리도 함께 조회되도록 수정
  src/main/java/com/codiary/backend/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/codiary/backend/global/repository/PostRepository.java
  src/main/java/com/codiary/backend/global/service/PostService/PostQueryServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/PostController.java
Labels: 🔨 Refactor

#132 #103 Feat: TeamProjectMapRepository 생성
  src/main/java/com/codiary/backend/global/repository/TeamProjectMapRepository.java
Labels: ✨ Feature

#135 #133 Fix : 팀 정보 조회 Lazy 로드 필드 초기화
  src/main/java/com/codiary/backend/global/service/TeamService/TeamQueryServiceImpl.java
Labels: 🎀 Fix

#137 Feat: 로그아웃 구현
  src/main/java/com/codiary/backend/BackendApplication.java
  src/main/java/com/codiary/backend/global/config/SecurityConfig.java
  src/main/java/com/codiary/backend/global/domain/entity/Token.java
  src/main/java/com/codiary/backend/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/codiary/backend/global/repository/TokenRepository.java
  src/main/java/com/codiary/backend/global/scheduler/TokenCleanupScheduler.java
  src/main/java/com/codiary/backend/global/service/MemberService/MemberCommandService.java
  src/main/java/com/codiary/backend/global/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/MemberController.java
  src/main/java/com/codiary/backend/global/web/controller/PostController.java
Labels: ✨ Feature

#138 Feature/#136 team project create
  src/main/java/com/codiary/backend/global/converter/TeamConverter.java
  src/main/java/com/codiary/backend/global/domain/entity/mapping/TeamProjectMap.java
  src/main/java/com/codiary/backend/global/domain/enums/MemberRole.java
  src/main/java/com/codiary/backend/global/service/TeamService/TeamCommandService.java
  src/main/java/com/codiary/backend/global/service/TeamService/TeamCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/service/TeamService/TeamQueryService.java
  src/main/java/com/codiary/backend/global/service/TeamService/TeamQueryServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/TeamController.java
  src/main/java/com/codiary/backend/global/web/dto/Team/TeamRequestDTO.java
  src/main/java/com/codiary/backend/global/web/dto/Team/TeamResponseDTO.java
Labels: ✨ Feature

#140 Feat: 댓글 기능 구현
  src/main/java/com/codiary/backend/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/codiary/backend/global/converter/CommentConverter.java
  src/main/java/com/codiary/backend/global/converter/PostConverter.java
  src/main/java/com/codiary/backend/global/domain/entity/Comment.java
  src/main/java/com/codiary/backend/global/repository/CommentRepository.java
  src/main/java/com/codiary/backend/global/service/CommentService/CommentCommandService.java
  src/main/java/com/codiary/backend/global/service/CommentService/CommentCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/service/PostService/PostCommandService.java
  src/main/java/com/codiary/backend/global/service/PostService/PostCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/CommentController.java
  src/main/java/com/codiary/backend/global/web/controller/PostController.java
  src/main/java/com/codiary/backend/global/web/dto/Comment/CommentRequestDTO.java
  src/main/java/com/codiary/backend/global/web/dto/Comment/CommentResponseDTO.java
  src/main/java/com/codiary/backend/global/web/dto/Post/PostRequestDTO.java
  src/main/java/com/codiary/backend/global/web/dto/Post/PostResponseDTO.java
Labels: ✨ Feature

#141 Feat: 메인페이지 Post 조회
  src/main/java/com/codiary/backend/global/converter/CommentConverter.java
  src/main/java/com/codiary/backend/global/converter/PostConverter.java
  src/main/java/com/codiary/backend/global/repository/PostRepository.java
  src/main/java/com/codiary/backend/global/service/CommentService/CommentCommandService.java
  src/main/java/com/codiary/backend/global/service/CommentService/CommentCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/service/PostService/PostCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/service/PostService/PostQueryService.java
  src/main/java/com/codiary/backend/global/service/PostService/PostQueryServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/CommentController.java
  src/main/java/com/codiary/backend/global/web/controller/PostController.java
  src/main/java/com/codiary/backend/global/web/dto/Post/PostResponseDTO.java
Labels: ✨ Feature

#142 Feature/#139 team follow
  src/main/java/com/codiary/backend/global/converter/TeamConverter.java
  src/main/java/com/codiary/backend/global/repository/TeamMemberRepository.java
  src/main/java/com/codiary/backend/global/service/TeamMemberService/TeamMemberCommandService.java
  src/main/java/com/codiary/backend/global/service/TeamMemberService/TeamMemberCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/service/TeamService/TeamCommandService.java
  src/main/java/com/codiary/backend/global/service/TeamService/TeamCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/service/TeamService/TeamQueryService.java
  src/main/java/com/codiary/backend/global/service/TeamService/TeamQueryServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/TeamController.java
  src/main/java/com/codiary/backend/global/web/controller/TeamMemberController.java
  src/main/java/com/codiary/backend/global/web/dto/Team/TeamResponseDTO.java
Labels: ✨ Feature

#144 feature/#143-team-admin-fix
  src/main/java/com/codiary/backend/global/converter/TeamConverter.java
  src/main/java/com/codiary/backend/global/service/TeamMemberService/TeamMemberCommandService.java
  src/main/java/com/codiary/backend/global/service/TeamMemberService/TeamMemberCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/service/TeamService/TeamCommandService.java
  src/main/java/com/codiary/backend/global/service/TeamService/TeamCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/service/TeamService/TeamQueryService.java
  src/main/java/com/codiary/backend/global/service/TeamService/TeamQueryServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/TeamController.java
  src/main/java/com/codiary/backend/global/web/controller/TeamMemberController.java
Labels: 🎀 Fix

#148 Refactor: 로그인 시 멤버 아이디 반환
  src/main/java/com/codiary/backend/global/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/web/dto/Member/MemberResponseDTO.java
Labels: 🔨 Refactor

#149 Feat: 팀 팔로워 목록 조회, 팀 팔로우 기능 구현
  src/main/java/com/codiary/backend/global/converter/TeamConverter.java
  src/main/java/com/codiary/backend/global/domain/entity/Member.java
  src/main/java/com/codiary/backend/global/domain/entity/Team.java
  src/main/java/com/codiary/backend/global/domain/entity/TeamFollow.java
  src/main/java/com/codiary/backend/global/repository/TeamFollowRepository.java
  src/main/java/com/codiary/backend/global/repository/TeamRepository.java
  src/main/java/com/codiary/backend/global/service/TeamService/TeamCommandService.java
  src/main/java/com/codiary/backend/global/service/TeamService/TeamCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/service/TeamService/TeamFollowService.java
  src/main/java/com/codiary/backend/global/service/TeamService/TeamQueryService.java
  src/main/java/com/codiary/backend/global/service/TeamService/TeamQueryServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/TeamController.java
  src/main/java/com/codiary/backend/global/web/dto/Team/TeamResponseDTO.java
  src/main/java/com/codiary/backend/global/web/dto/Team/TeamSumResponseDTO.java
Labels: ✨ Feature

#151 Fix: 팀 팔로우 및 취소 기능 수정
  src/main/java/com/codiary/backend/global/service/TeamService/TeamCommandServiceImpl.java
Labels: 🎀 Fix

#153 Fix: 팀 팔로우 기능 코드 수정
  src/main/java/com/codiary/backend/global/service/TeamService/TeamCommandServiceImpl.java
Labels: 🎀 Fix

#155 Fix: 팀 팔로우 기능 코드 수정
  src/main/java/com/codiary/backend/global/service/TeamService/TeamCommandServiceImpl.java
Labels: 🎀 Fix

#158 Fix: 팀 팔로우 취소 기능 코드 수정
  src/main/java/com/codiary/backend/global/service/TeamService/TeamFollowService.java
Labels: 🎀 Fix

#159 Fix: authorization 없이 API 접근 가능
  src/main/java/com/codiary/backend/global/config/SecurityConfig.java
Labels: 🎀 Fix

#161 Fix: 팀 팔로워 목록 조회 코드 수정
  src/main/java/com/codiary/backend/global/service/TeamService/TeamQueryServiceImpl.java
Labels: 🎀 Fix

#164 Refactor: 프로젝트 리스트 조회, 키워드 검색으로 카테고리 리스트 조회 Api 토큰 없이 접근 하도록 수정
  src/main/java/com/codiary/backend/global/config/SecurityConfig.java
  src/main/java/com/codiary/backend/global/converter/PostConverter.java
  src/main/java/com/codiary/backend/global/domain/entity/Post.java
  src/main/java/com/codiary/backend/global/web/controller/CategoryController.java
  src/main/java/com/codiary/backend/global/web/controller/ProjectController.java
Labels: 🔨 Refactor

#165 Feat: 팀 프로젝트 생성 로직 구현
  src/main/java/com/codiary/backend/global/service/TeamService/TeamCommandService.java
  src/main/java/com/codiary/backend/global/service/TeamService/TeamCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/TeamController.java
  src/main/java/com/codiary/backend/global/web/dto/Team/TeamRequestDTO.java
  src/main/java/com/codiary/backend/global/web/dto/Team/TeamResponseDTO.java
Labels: ✨ Feature

#168 Chore: workflow 수정
  .github/workflows/cicd.yml
Labels: 🛠️ Chore

#169 Fix: 캘린더 조회 기능 수정
  README.md
  src/main/java/com/codiary/backend/global/service/PostService/PostQueryService.java
  src/main/java/com/codiary/backend/global/service/PostService/PostQueryServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/CalendarController.java
Labels: 🎀 Fix

#171 Feat: 검색 기능 구현
  src/main/java/com/codiary/backend/global/config/SecurityConfig.java
  src/main/java/com/codiary/backend/global/converter/PostConverter.java
  src/main/java/com/codiary/backend/global/repository/PostRepository.java
  src/main/java/com/codiary/backend/global/service/PostService/PostQueryService.java
  src/main/java/com/codiary/backend/global/service/PostService/PostQueryServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/PostController.java
  src/main/java/com/codiary/backend/global/web/dto/Post/PostResponseDTO.java
Labels: ✨ Feature

#172 Feat: 카카오 로그인 구현
  src/main/java/com/codiary/backend/global/config/SecurityConfig.java
  src/main/java/com/codiary/backend/global/jwt/JwtTokenProvider.java
  src/main/java/com/codiary/backend/global/service/MemberService/SocialLoginService.java
  src/main/java/com/codiary/backend/global/web/controller/SocialLoginController.java
  src/main/java/com/codiary/backend/global/web/dto/SocialLogin/Oauth2ResponseDTO.java
Labels: ✨ Feature

#175 Fix: 프로젝트 추가 관련 에러 수정
  src/main/java/com/codiary/backend/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/codiary/backend/global/converter/MemberConverter.java
  src/main/java/com/codiary/backend/global/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/service/MemberService/MemberQueryServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/MemberController.java
Labels: 🎀 Fix

#179 Refactor: Post의 Entity내의 카테고리 항목 EAGER에서 LAZY fetch로 변경 및 Repository 쿼리문 수정
  src/main/java/com/codiary/backend/global/domain/entity/Post.java
  src/main/java/com/codiary/backend/global/repository/PostRepository.java
Labels: 🔨 Refactor

#180 Refactor: Post 엔티티 내의 불필요한 EAGER FetchType 제거
  src/main/java/com/codiary/backend/global/domain/entity/Post.java
Labels: 🔨 Refactor

#181 Fix/#177 팀 관리자 권한 수정
  src/main/java/com/codiary/backend/global/service/TeamMemberService/TeamMemberCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/service/TeamService/TeamCommandServiceImpl.java
Labels: 🎀 Fix

#183 Fix: 팀 생성 메서드에 팀 멤버리스트 초기화
  src/main/java/com/codiary/backend/global/service/TeamService/TeamCommandServiceImpl.java
Labels: 🎀 Fix

#186 Fix: 팀원 삭제 기능 오류 수정
  src/main/java/com/codiary/backend/global/service/TeamMemberService/TeamMemberCommandServiceImpl.java
Labels: 🎀 Fix

#188 Refactor: Post Entity 수정 - postBody 크기 varchar(3000)으로 확장
  src/main/java/com/codiary/backend/global/domain/entity/Post.java
  src/main/java/com/codiary/backend/global/repository/PostRepository.java
Labels: 🔨 Refactor

#189 Fix: 팀 팔로우 및 프로필 수정 권한 분리 로직 수정
  src/main/java/com/codiary/backend/global/converter/TeamConverter.java
  src/main/java/com/codiary/backend/global/service/TeamService/TeamQueryServiceImpl.java
  src/main/java/com/codiary/backend/global/web/dto/Team/TeamResponseDTO.java
Labels: 🎀 Fix

#190 Feat: 팀 설정을 위한 팀 전체 리스트 조회 Api 기능 구현
  src/main/java/com/codiary/backend/global/config/SecurityConfig.java
  src/main/java/com/codiary/backend/global/converter/TeamConverter.java
  src/main/java/com/codiary/backend/global/repository/PostRepository.java
  src/main/java/com/codiary/backend/global/repository/TeamRepository.java
  src/main/java/com/codiary/backend/global/service/TeamService/TeamQueryService.java
  src/main/java/com/codiary/backend/global/service/TeamService/TeamQueryServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/TeamController.java
  src/main/java/com/codiary/backend/global/web/dto/Team/TeamResponseDTO.java
Labels: ✨ Feature

#191 Feat: 팀 ID 추가 반환
  src/main/java/com/codiary/backend/global/converter/MemberConverter.java
  src/main/java/com/codiary/backend/global/service/MemberService/FollowService.java
  src/main/java/com/codiary/backend/global/service/MemberService/FollowServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/MemberController.java
  src/main/java/com/codiary/backend/global/web/dto/Member/FollowResponseDto.java
  src/main/java/com/codiary/backend/global/web/dto/Member/MemberResponseDTO.java
Labels: 📬 API

#196 Fix: 팔로우 기능 관련 에러 해결
  src/main/java/com/codiary/backend/global/repository/MemberRepository.java
  src/main/java/com/codiary/backend/global/service/MemberService/FollowServiceImpl.java
Labels: 🎀 Fix, 📬 API

#201 #200 Feat: Post 상세 조회 기능 구현
  src/main/java/com/codiary/backend/global/converter/PostConverter.java
  src/main/java/com/codiary/backend/global/service/PostService/PostQueryService.java
  src/main/java/com/codiary/backend/global/service/PostService/PostQueryServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/PostController.java
  src/main/java/com/codiary/backend/global/web/dto/Post/PostResponseDTO.java
Labels: ✨ Feature

#202 Fix: 팀 멤버 역할 수정 및 팀원 닉네임 반환 로직 수정
  src/main/java/com/codiary/backend/global/converter/TeamConverter.java
  src/main/java/com/codiary/backend/global/domain/entity/mapping/TeamMember.java
  src/main/java/com/codiary/backend/global/service/TeamMemberService/TeamMemberCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/service/TeamService/TeamQueryServiceImpl.java
  src/main/java/com/codiary/backend/global/web/dto/TeamMember/TeamMemberRequestDTO.java
  src/main/java/com/codiary/backend/global/web/dto/TeamMember/TeamMemberResponseDTO.java
Labels: 🎀 Fix

#206 Fix: 팀 프로젝트 리스트 로직 수정
  src/main/java/com/codiary/backend/global/converter/TeamConverter.java
  src/main/java/com/codiary/backend/global/converter/TeamMemberConverter.java
  src/main/java/com/codiary/backend/global/service/TeamService/TeamQueryServiceImpl.java
  src/main/java/com/codiary/backend/global/web/dto/Team/TeamResponseDTO.java
Labels: 🎀 Fix

#205 Fix: 오타 수정
  src/main/java/com/codiary/backend/global/service/MemberService/SocialLoginService.java
Labels: 🎀 Fix

#209 Fix: 팀프로젝트목록 초기화
  src/main/java/com/codiary/backend/global/service/TeamService/TeamQueryServiceImpl.java
Labels: 🎀 Fix

#211 Feat: 소셜 로그인 Tag 추가
  src/main/java/com/codiary/backend/global/web/controller/SocialLoginController.java
Labels: ✨ Feature

#212 Fix: 게시글의 댓글&대댓글 조회
  src/main/java/com/codiary/backend/global/domain/entity/Bookmark.java
  src/main/java/com/codiary/backend/global/domain/entity/mapping/MemberCategory.java
  src/main/java/com/codiary/backend/global/repository/BookmarkRepository.java
  src/main/java/com/codiary/backend/global/repository/CommentRepository.java
  src/main/java/com/codiary/backend/global/repository/PostRepository.java
  src/main/java/com/codiary/backend/global/service/CommentService/CommentCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/service/MemberCategoryService/MemberCategoryCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/service/PostService/PostCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/service/PostService/PostQueryServiceImpl.java
Labels: 🎀 Fix, 🐞 BugFix

#213 Refactor: 인접한 다이어리 조회시 작성자 닉네임도 반환하도록 수정
  src/main/java/com/codiary/backend/global/converter/PostConverter.java
  src/main/java/com/codiary/backend/global/web/dto/Post/PostResponseDTO.java
Labels: 🔨 Refactor

#214 Refactor: 인접한 다이어리 조회시 닉네임 반환 오류 발생으로 반환 안하도록 재수정
  src/main/java/com/codiary/backend/global/converter/PostConverter.java
Labels: 🔨 Refactor

#215 Refactor: 인접한 다이어리 조회 재수정
  src/main/java/com/codiary/backend/global/converter/PostConverter.java
Labels: 🔨 Refactor

#216 Refactor: Post Entity 수정
  src/main/java/com/codiary/backend/global/domain/entity/Post.java
  src/main/java/com/codiary/backend/global/repository/PostRepository.java
Labels: 🔨 Refactor

#218 Refactor: SecurityConfig 파일 수정
  src/main/java/com/codiary/backend/global/config/SecurityConfig.java
Labels: 🔨 Refactor

#219 Refactor: SecurityConfig 파일 추가 수정
  src/main/java/com/codiary/backend/global/config/SecurityConfig.java
Labels: 🔨 Refactor

#220 Refactor: SecurityConfig 재수정
  src/main/java/com/codiary/backend/global/config/SecurityConfig.java
Labels: 🔨 Refactor

#221 Refactor: SecurityConfig 파일 수정 및 주석 제
  src/main/java/com/codiary/backend/global/config/SecurityConfig.java
  src/main/java/com/codiary/backend/global/domain/entity/Team.java
  src/main/java/com/codiary/backend/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/codiary/backend/global/repository/PostRepository.java
  src/main/java/com/codiary/backend/global/web/controller/PostController.java
Labels: 🔨 Refactor
