Repository Codiary-UMC-6th/Backend-Codiary, pull requests merged in 2024-07, with the labels that each got.

#2 Chore: 프로젝트 초기 환경 세팅
  .gitignore
  Dockerfile
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/codiary/backend/BackendApplication.java
  src/main/java/com/codiary/backend/global/config/SwaggerConfig.java
  src/test/java/com/codiary/backend/BackendApplicationTests.java
Labels: ⚙ Setting

#5 Fix: BaseEntity 수정
  src/main/java/com/codiary/backend/global/domain/common/BaseEntity.java
Labels: 🎀 Fix

#7 Feat: Diary 컨트롤러에 API 기능별 swagger 엔드포인트 명세
  src/main/java/com/codiary/backend/global/web/controller/DiaryController.java
Labels: ✨ Feature

#11 #10 Refactor: Add Annotation to every Entities
  src/main/java/com/codiary/backend/global/domain/entity/Comment.java
  src/main/java/com/codiary/backend/global/domain/entity/Diary.java
  src/main/java/com/codiary/backend/global/domain/entity/DiaryPhoto.java
  src/main/java/com/codiary/backend/global/domain/entity/Member.java
  src/main/java/com/codiary/backend/global/domain/entity/Project.java
  src/main/java/com/codiary/backend/global/domain/entity/Team.java
  src/main/java/com/codiary/backend/global/domain/entity/mapping/Authors.java
  src/main/java/com/codiary/backend/global/domain/entity/mapping/Categories.java
  src/main/java/com/codiary/backend/global/domain/entity/mapping/MemberProjectMap.java
  src/main/java/com/codiary/backend/global/domain/entity/mapping/TeamMember.java
  src/main/java/com/codiary/backend/global/domain/entity/mapping/TeamProjectMap.java
Labels: 🔨 Refactor

#12 #10 Refactor: Comment 엔티티의 매핑 관계에서 diary_id를 post_id로 다시 변경
  src/main/java/com/codiary/backend/global/domain/entity/Comment.java
Labels: 🔨 Refactor

#15 #13 Refactor: 엔티티 및 기타 프로젝트 파일에서 Diary를 모두 Post로 변경
  src/main/java/com/codiary/backend/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/codiary/backend/global/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/codiary/backend/global/converter/PostConverter.java
  src/main/java/com/codiary/backend/global/converter/PostPhotoConverter.java
  src/main/java/com/codiary/backend/global/domain/entity/Comment.java
  src/main/java/com/codiary/backend/global/domain/entity/Member.java
  src/main/java/com/codiary/backend/global/domain/entity/Post.java
  src/main/java/com/codiary/backend/global/domain/entity/PostPhoto.java
  src/main/java/com/codiary/backend/global/domain/entity/Team.java
  src/main/java/com/codiary/backend/global/domain/entity/mapping/Authors.java
  src/main/java/com/codiary/backend/global/domain/entity/mapping/Categories.java
  src/main/java/com/codiary/backend/global/repository/PostPhotoRepository.java
  src/main/java/com/codiary/backend/global/repository/PostRepository.java
  src/main/java/com/codiary/backend/global/service/DiaryPhotoService/DiaryPhotoCommandService.java
  src/main/java/com/codiary/backend/global/service/DiaryPhotoService/DiaryPhotoCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/service/DiaryPhotoService/DiaryPhotoQueryService.java
  src/main/java/com/codiary/backend/global/service/DiaryPhotoService/DiaryPhotoQueryServiceImpl.java
  src/main/java/com/codiary/backend/global/service/DiaryService/DiaryCommandService.java
  src/main/java/com/codiary/backend/global/service/DiaryService/DiaryCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/service/DiaryService/DiaryQueryService.java
  src/main/java/com/codiary/backend/global/service/DiaryService/DiaryQueryServiceImpl.java
  src/main/java/com/codiary/backend/global/service/PostPhotoService/PostPhotoCommandService.java
  src/main/java/com/codiary/backend/global/service/PostPhotoService/PostPhotoCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/service/PostPhotoService/PostPhotoQueryService.java
  src/main/java/com/codiary/backend/global/service/PostPhotoService/PostPhotoQueryServiceImpl.java
  src/main/java/com/codiary/backend/global/service/PostService/PostCommandService.java
  src/main/java/com/codiary/backend/global/service/PostService/PostCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/service/PostService/PostQueryService.java
  src/main/java/com/codiary/backend/global/service/PostService/PostQueryServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/PostController.java
  src/main/java/com/codiary/backend/global/web/controller/PostPhotoController.java
  src/main/java/com/codiary/backend/global/web/dto/Diary/DiaryRequestDTO.java
  src/main/java/com/codiary/backend/global/web/dto/Diary/DiaryResponseDTO.java
  src/main/java/com/codiary/backend/global/web/dto/DiaryPhoto/DiaryPhotoRequestDTO.java
  src/main/java/com/codiary/backend/global/web/dto/DiaryPhoto/DiaryPhotoResponseDTO.java
  src/main/java/com/codiary/backend/global/web/dto/Post/PostRequestDTO.java
  src/main/java/com/codiary/backend/global/web/dto/Post/PostResponseDTO.java
  src/main/java/com/codiary/backend/global/web/dto/PostPhoto/PostPhotoRequestDTO.java
  src/main/java/com/codiary/backend/global/web/dto/PostPhoto/PostPhotoResponseDTO.java
Labels: 🔨 Refactor

#16 Refactor: Entity 리팩토링
  src/main/java/com/codiary/backend/global/domain/entity/Comment.java
  src/main/java/com/codiary/backend/global/domain/entity/Member.java
  src/main/java/com/codiary/backend/global/domain/entity/Post.java
  src/main/java/com/codiary/backend/global/domain/entity/PostPhoto.java
  src/main/java/com/codiary/backend/global/domain/entity/Project.java
  src/main/java/com/codiary/backend/global/domain/entity/Team.java
  src/main/java/com/codiary/backend/global/domain/entity/mapping/Authors.java
  src/main/java/com/codiary/backend/global/domain/entity/mapping/Categories.java
  src/main/java/com/codiary/backend/global/domain/entity/mapping/MemberProjectMap.java
  src/main/java/com/codiary/backend/global/domain/entity/mapping/TeamMember.java
  src/main/java/com/codiary/backend/global/domain/entity/mapping/TeamProjectMap.java
  src/main/java/com/codiary/backend/global/domain/entity/mapping/TechStacks.java
Labels: 🎀 Fix, 🔨 Refactor

#21 Feat: 포스트 글 작성 기능 구현
  src/main/java/com/codiary/backend/global/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/codiary/backend/global/converter/PostConverter.java
  src/main/java/com/codiary/backend/global/domain/entity/Post.java
  src/main/java/com/codiary/backend/global/repository/MemberRepository.java
  src/main/java/com/codiary/backend/global/repository/PostRepository.java
  src/main/java/com/codiary/backend/global/service/PostService/PostCommandService.java
  src/main/java/com/codiary/backend/global/service/PostService/PostCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/PostController.java
  src/main/java/com/codiary/backend/global/web/dto/Post/PostRequestDTO.java
  src/main/java/com/codiary/backend/global/web/dto/Post/PostResponseDTO.java
Labels: ✨ Feature

#25 Feat: 포스트 글 수정 기능 구현
  src/main/java/com/codiary/backend/global/converter/PostConverter.java
  src/main/java/com/codiary/backend/global/domain/entity/Post.java
  src/main/java/com/codiary/backend/global/service/PostService/PostCommandService.java
  src/main/java/com/codiary/backend/global/service/PostService/PostCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/PostController.java
  src/main/java/com/codiary/backend/global/web/dto/Post/PostRequestDTO.java
  src/main/java/com/codiary/backend/global/web/dto/Post/PostResponseDTO.java
Labels: ✨ Feature

#28 Feat: 포스트 상세 조회 및 삭제 기능 구현
  src/main/java/com/codiary/backend/global/converter/PostConverter.java
  src/main/java/com/codiary/backend/global/repository/PostRepository.java
  src/main/java/com/codiary/backend/global/service/PostService/PostCommandService.java
  src/main/java/com/codiary/backend/global/service/PostService/PostCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/service/PostService/PostQueryService.java
  src/main/java/com/codiary/backend/global/service/PostService/PostQueryServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/PostController.java
  src/main/java/com/codiary/backend/global/web/dto/Post/PostResponseDTO.java
Labels: ✨ Feature

#33 Feat: 글 포스팅 관련 부가 기능 구현
  src/main/java/com/codiary/backend/global/converter/PostConverter.java
  src/main/java/com/codiary/backend/global/domain/entity/Post.java
  src/main/java/com/codiary/backend/global/domain/entity/mapping/Authors.java
  src/main/java/com/codiary/backend/global/service/PostService/PostCommandService.java
  src/main/java/com/codiary/backend/global/service/PostService/PostCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/PostController.java
  src/main/java/com/codiary/backend/global/web/dto/Post/PostRequestDTO.java
  src/main/java/com/codiary/backend/global/web/dto/Post/PostResponseDTO.java
Labels: ✨ Feature

#29 Feat: 회원가입 및 로그인 기능 구현
  build.gradle
  src/main/java/com/codiary/backend/BackendApplication.java
  src/main/java/com/codiary/backend/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/codiary/backend/global/config/SecurityConfig.java
  src/main/java/com/codiary/backend/global/config/SwaggerConfig.java
  src/main/java/com/codiary/backend/global/domain/entity/Member.java
  src/main/java/com/codiary/backend/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/codiary/backend/global/jwt/JwtTokenProvider.java
  src/main/java/com/codiary/backend/global/jwt/SecurityUtil.java
  src/main/java/com/codiary/backend/global/jwt/TokenInfo.java
  src/main/java/com/codiary/backend/global/repository/MemberRepository.java
  src/main/java/com/codiary/backend/global/service/MemberService/CustomMemberDetailsService.java
  src/main/java/com/codiary/backend/global/service/MemberService/MemberCommandService.java
  src/main/java/com/codiary/backend/global/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/MemberController.java
  src/main/java/com/codiary/backend/global/web/dto/Member/MemberRequestDTO.java
  src/main/java/com/codiary/backend/global/web/dto/Member/MemberResponseDTO.java
Labels: ✨ Feature

#36 #35 Chore: CI/CD 구축
  .github/workflows/cicd.yml
  Dockerfile
  build.gradle
Labels: 🛠️ Chore

#39 Refactor: Post 관련 컨트롤러 추가 및 엔드포인트 수정
  src/main/java/com/codiary/backend/global/web/controller/PostController.java
Labels: 🔨 Refactor

#40 Feat: 다이어리 조회 관련 API에서 결과 리스트를 페이징으로 조회하도록 구현 및 수정
  src/main/java/com/codiary/backend/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/codiary/backend/global/apiPayload/exception/handler/PostHandler.java
  src/main/java/com/codiary/backend/global/converter/PostConverter.java
  src/main/java/com/codiary/backend/global/repository/PostRepository.java
  src/main/java/com/codiary/backend/global/repository/ProjectRepository.java
  src/main/java/com/codiary/backend/global/service/PostService/PostQueryService.java
  src/main/java/com/codiary/backend/global/service/PostService/PostQueryServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/PostController.java
  src/main/java/com/codiary/backend/global/web/dto/Post/PostResponseDTO.java
Labels: ✨ Feature, 🔨 Refactor

#42 Refactor: 포스트 글 생성시 프로젝트 항목 추가 및 PostConverter에서 누락된 항목 추가
  src/main/java/com/codiary/backend/global/converter/PostConverter.java
  src/main/java/com/codiary/backend/global/domain/entity/Post.java
  src/main/java/com/codiary/backend/global/service/PostService/PostCommandService.java
  src/main/java/com/codiary/backend/global/service/PostService/PostCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/PostController.java
  src/main/java/com/codiary/backend/global/web/dto/Post/PostRequestDTO.java
Labels: 🔨 Refactor

#44 Feat: 캘린더 조회 데이터 변경 및 프로젝트 별 글 제목 조회 기능 추가
  src/main/java/com/codiary/backend/global/converter/CalendarConverter.java
  src/main/java/com/codiary/backend/global/repository/PostRepository.java
  src/main/java/com/codiary/backend/global/service/PostService/PostQueryService.java
  src/main/java/com/codiary/backend/global/service/PostService/PostQueryServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/CalendarController.java
  src/main/java/com/codiary/backend/global/web/dto/Calendar/CalendarDTO.java
Labels: ✨ Feature, 📬 API

#45 Chore: CI/CD 속도 개선
  .github/workflows/cicd.yml
Labels: 🛠️ Chore

#47 Feat: 인접한 다이어리 조회 기능 구현
  src/main/java/com/codiary/backend/global/converter/PostConverter.java
  src/main/java/com/codiary/backend/global/domain/entity/Post.java
  src/main/java/com/codiary/backend/global/repository/PostRepository.java
  src/main/java/com/codiary/backend/global/service/PostService/PostQueryService.java
  src/main/java/com/codiary/backend/global/service/PostService/PostQueryServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/PostController.java
  src/main/java/com/codiary/backend/global/web/dto/Post/PostResponseDTO.java
Labels: ✨ Feature, 🔨 Refactor

#49 Feature/#37 post file saving
  build.gradle
  src/main/java/com/codiary/backend/global/config/S3Config.java
  src/main/java/com/codiary/backend/global/converter/PostConverter.java
  src/main/java/com/codiary/backend/global/converter/PostFileConverter.java
  src/main/java/com/codiary/backend/global/converter/PostPhotoConverter.java
  src/main/java/com/codiary/backend/global/domain/entity/Post.java
  src/main/java/com/codiary/backend/global/domain/entity/PostFile.java
  src/main/java/com/codiary/backend/global/domain/entity/PostPhoto.java
  src/main/java/com/codiary/backend/global/domain/entity/Uuid.java
  src/main/java/com/codiary/backend/global/repository/PostFileRepository.java
  src/main/java/com/codiary/backend/global/repository/PostPhotoRepository.java
  src/main/java/com/codiary/backend/global/repository/PostRepository.java
  src/main/java/com/codiary/backend/global/repository/UuidRepository.java
  src/main/java/com/codiary/backend/global/s3/AmazonS3Manager.java
  src/main/java/com/codiary/backend/global/service/PostFileService/PostFileCommandService.java
  src/main/java/com/codiary/backend/global/service/PostFileService/PostFileCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/service/PostFileService/PostFileQueryService.java
  src/main/java/com/codiary/backend/global/service/PostFileService/PostFileQueryServiceImpl.java
  src/main/java/com/codiary/backend/global/service/PostPhotoService/PostPhotoCommandService.java
  src/main/java/com/codiary/backend/global/service/PostPhotoService/PostPhotoCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/service/PostPhotoService/PostPhotoQueryService.java
  src/main/java/com/codiary/backend/global/service/PostPhotoService/PostPhotoQueryServiceImpl.java
  src/main/java/com/codiary/backend/global/service/PostService/PostCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/PostController.java
  src/main/java/com/codiary/backend/global/web/controller/PostFileController.java
  src/main/java/com/codiary/backend/global/web/dto/Post/PostRequestDTO.java
  src/main/java/com/codiary/backend/global/web/dto/Post/PostResponseDTO.java
  src/main/java/com/codiary/backend/global/web/dto/PostFile/PostFileRequestDTO.java
  src/main/java/com/codiary/backend/global/web/dto/PostFile/PostFileResponseDTO.java
  src/main/java/com/codiary/backend/global/web/dto/PostPhoto/PostPhotoRequestDTO.java
  src/main/java/com/codiary/backend/global/web/dto/PostPhoto/PostPhotoResponseDTO.java
Labels: ✨ Feature

#53 Feat: 작성한 글의 카테고리 설정 및 카테고리 리스트에 항목 추가 기능 구현
  src/main/java/com/codiary/backend/global/converter/PostConverter.java
  src/main/java/com/codiary/backend/global/domain/entity/Post.java
  src/main/java/com/codiary/backend/global/domain/entity/mapping/Categories.java
  src/main/java/com/codiary/backend/global/repository/CategoriesRepository.java
  src/main/java/com/codiary/backend/global/service/CategoryService/CategoryCommandService.java
  src/main/java/com/codiary/backend/global/service/CategoryService/CategoryCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/service/CategoryService/CategoryQueryService.java
  src/main/java/com/codiary/backend/global/service/CategoryService/CategoryQueryServiceImpl.java
  src/main/java/com/codiary/backend/global/service/PostService/PostCommandService.java
  src/main/java/com/codiary/backend/global/service/PostService/PostCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/CategoriesController.java
  src/main/java/com/codiary/backend/global/web/controller/PostController.java
  src/main/java/com/codiary/backend/global/web/dto/Category/CategoryRequestDTO.java
  src/main/java/com/codiary/backend/global/web/dto/Category/CategoryResponseDTO.java
  src/main/java/com/codiary/backend/global/web/dto/Post/PostRequestDTO.java
Labels: ✨ Feature

#54 Refactor: Import 누락된 부분 다시 추가
  src/main/java/com/codiary/backend/global/web/dto/Post/PostRequestDTO.java
Labels: 🔨 Refactor

#57 Feat: 내 다이어리 조회 페이지네이션 기능 개발
  src/main/java/com/codiary/backend/global/repository/PostRepository.java
  src/main/java/com/codiary/backend/global/service/MemberService/MemberQueryService.java
  src/main/java/com/codiary/backend/global/service/MemberService/MemberQueryServiceImpl.java
  src/main/java/com/codiary/backend/global/service/PostService/PostQueryServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/MemberController.java
Labels: ✨ Feature

#58 #26 Feat: 북마크 기능
  src/main/java/com/codiary/backend/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/codiary/backend/global/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/codiary/backend/global/apiPayload/exception/handler/BookmarkHandler.java
  src/main/java/com/codiary/backend/global/converter/BookmarkConverter.java
  src/main/java/com/codiary/backend/global/converter/MemberConverter.java
  src/main/java/com/codiary/backend/global/domain/entity/Bookmark.java
  src/main/java/com/codiary/backend/global/domain/entity/Member.java
  src/main/java/com/codiary/backend/global/domain/entity/Post.java
  src/main/java/com/codiary/backend/global/repository/BookmarkRepository.java
  src/main/java/com/codiary/backend/global/service/BookmarkService/BookmarkCommandService.java
  src/main/java/com/codiary/backend/global/service/BookmarkService/BookmarkCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/service/MemberService/MemberQueryService.java
  src/main/java/com/codiary/backend/global/service/MemberService/MemberQueryServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/BookmarkController.java
  src/main/java/com/codiary/backend/global/web/controller/MemberController.java
  src/main/java/com/codiary/backend/global/web/dto/Bookmark/BookmarkResponseDTO.java
  src/main/java/com/codiary/backend/global/web/dto/Member/MemberResponseDTO.java
Labels: ✨ Feature

#60 Feat: 카테고리명으로 다이어리 리스트 페이징 조회 기능 구현 & Refactor: Post, Categories, Member 엔티티 수정
  src/main/java/com/codiary/backend/global/converter/PostConverter.java
  src/main/java/com/codiary/backend/global/domain/entity/Member.java
  src/main/java/com/codiary/backend/global/domain/entity/Post.java
  src/main/java/com/codiary/backend/global/domain/entity/mapping/Categories.java
  src/main/java/com/codiary/backend/global/repository/PostRepository.java
  src/main/java/com/codiary/backend/global/service/PostService/PostCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/service/PostService/PostQueryService.java
  src/main/java/com/codiary/backend/global/service/PostService/PostQueryServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/PostController.java
Labels: ✨ Feature, 🔨 Refactor

#62 Refactor: Post관련 Api swagger 명세 description 수정
  src/main/java/com/codiary/backend/global/web/controller/PostController.java
Labels: 🔨 Refactor

#64 Refactor: 다이어리 생성시 카테고리 설정을 하지 않도록 수정
  src/main/java/com/codiary/backend/global/converter/PostConverter.java
  src/main/java/com/codiary/backend/global/domain/entity/Post.java
  src/main/java/com/codiary/backend/global/web/controller/PostController.java
  src/main/java/com/codiary/backend/global/web/dto/Post/PostRequestDTO.java
Labels: 🔨 Refactor

#66 Feat: 키워드 입력을 통해 관련 카테고리 리스트 조회 기능 구현
  src/main/java/com/codiary/backend/global/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/codiary/backend/global/converter/CategoryConverter.java
  src/main/java/com/codiary/backend/global/domain/entity/mapping/Categories.java
  src/main/java/com/codiary/backend/global/repository/CategoryRepository.java
  src/main/java/com/codiary/backend/global/service/CategoryService/CategoryCommandServiceImpl.java
  src/main/java/com/codiary/backend/global/service/CategoryService/CategoryQueryService.java
  src/main/java/com/codiary/backend/global/service/CategoryService/CategoryQueryServiceImpl.java
  src/main/java/com/codiary/backend/global/web/controller/CategoriesController.java
  src/main/java/com/codiary/backend/global/web/controller/CategoryController.java
  src/main/java/com/codiary/backend/global/web/dto/Category/CategoryResponseDTO.java
Labels: ✨ Feature

#67 Refactor: PostController 코드 최적화
  src/main/java/com/codiary/backend/global/web/controller/PostController.java
Labels: 🔨 Refactor
