Repository Codiary-UMC-6th/Backend-Codiary, pull requests merged in 2025-02, with the labels that each got.

#324 Fix: 사용자별 프로젝트 조회 API 수정
  src/main/java/com/codiary/backend/domain/project/controller/ProjectController.java
  src/main/java/com/codiary/backend/domain/project/service/ProjectService.java
Labels: 🎀 Fix

#311 Refactor: 프리뷰 사용하는 부분 통합
  src/main/java/com/codiary/backend/domain/alert/service/AlertService.java
  src/main/java/com/codiary/backend/domain/post/controller/PostController.java
  src/main/java/com/codiary/backend/domain/post/converter/PostConverter.java
  src/main/java/com/codiary/backend/domain/post/dto/response/PostResponseDTO.java
  src/main/java/com/codiary/backend/domain/post/repository/PostRepository.java
  src/main/java/com/codiary/backend/domain/post/repository/PostRepositoryCustom.java
  src/main/java/com/codiary/backend/domain/post/repository/PostRepositoryImpl.java
  src/main/java/com/codiary/backend/domain/post/service/PostQueryService.java
Labels: ✨ Feature

#334 Feat: 사용자가 속한 팀 목록 조회 API 구현
  src/main/java/com/codiary/backend/domain/member/controller/MemberController.java
  src/main/java/com/codiary/backend/domain/member/dto/response/MemberResponseDTO.java
  src/main/java/com/codiary/backend/domain/member/service/MemberQueryService.java
  src/main/java/com/codiary/backend/domain/team/controller/TeamController.java
  src/main/java/com/codiary/backend/domain/team/converter/TeamConverter.java
  src/main/java/com/codiary/backend/domain/team/repository/TeamMemberRepository.java
  src/main/java/com/codiary/backend/domain/team/repository/TeamRepository.java
  src/main/java/com/codiary/backend/domain/team/service/TeamMemberService.java
  src/main/java/com/codiary/backend/domain/team/service/TeamService.java
Labels: ✨ Feature

#327 Test: 사용자 기본 프로필 정보 조회 테스트 코드 작성
  build.gradle
  src/main/java/com/codiary/backend/domain/member/controller/MemberController.java
  src/main/java/com/codiary/backend/domain/member/entity/Member.java
  src/main/java/com/codiary/backend/domain/member/service/MemberQueryService.java
  src/main/java/com/codiary/backend/global/apiPayload/exception/GeneralException.java
  src/test/java/com/codiary/backend/domain/member/controller/MemberControllerTest.java
  src/test/java/com/codiary/backend/domain/member/entity/MemberTest.java
  src/test/java/com/codiary/backend/domain/member/service/MemberQueryServiceTest.java
  src/test/java/com/codiary/backend/domain/member/util/MemberUtilTest.java
  src/test/java/com/codiary/backend/global/util/ControllerTest.java
Labels: ✅ Test

#335 Refactor: 팀 프로필 조회시 조회한 사용자가 팀의 ADMIN인지 여부 확인 응답 추가
  src/main/java/com/codiary/backend/domain/team/controller/TeamController.java
  src/main/java/com/codiary/backend/domain/team/converter/TeamConverter.java
  src/main/java/com/codiary/backend/domain/team/dto/response/TeamResponseDTO.java
  src/main/java/com/codiary/backend/domain/team/service/TeamMemberService.java
Labels: 🔨 Refactor

#337 fix: 사용자 프로필 설정 오류 수정
  src/main/java/com/codiary/backend/domain/member/entity/MemberImage.java
  src/main/java/com/codiary/backend/domain/member/service/MemberCommandService.java
Labels: 🎀 Fix
