Repository Codiary-UMC-6th/Backend-Codiary, pull requests merged in 2025-01, with the labels that each got.

#278 Feat: 특정 게시글 조회 API 기능 구현
  src/main/java/com/codiary/backend/domain/post/controller/PostController.java
  src/main/java/com/codiary/backend/domain/post/service/PostQueryService.java
Labels: ✨ Feature

#295 Refactor: Post 조회시 접근 관련 예외 처리
  src/main/java/com/codiary/backend/domain/member/repository/MemberRepository.java
  src/main/java/com/codiary/backend/domain/post/controller/PostController.java
  src/main/java/com/codiary/backend/domain/post/converter/PostConverter.java
  src/main/java/com/codiary/backend/domain/post/dto/response/PostResponseDTO.java
  src/main/java/com/codiary/backend/domain/post/repository/PostRepository.java
  src/main/java/com/codiary/backend/domain/post/service/PostCommandService.java
  src/main/java/com/codiary/backend/domain/post/service/PostQueryService.java
  src/main/java/com/codiary/backend/global/apiPayload/code/status/ErrorStatus.java
Labels: 🔨 Refactor

#302 Feat: 검색 정렬 조건 추가 & 카테고리 검색 기능 추가 개발
  src/main/java/com/codiary/backend/domain/category/controller/CategoryController.java
  src/main/java/com/codiary/backend/domain/category/converter/CategoryConverter.java
  src/main/java/com/codiary/backend/domain/category/dto/CategoryResponseDTO.java
  src/main/java/com/codiary/backend/domain/category/repository/CategoryRepository.java
  src/main/java/com/codiary/backend/domain/category/service/CategoryService.java
  src/main/java/com/codiary/backend/domain/post/controller/PostController.java
  src/main/java/com/codiary/backend/domain/post/repository/PostRepositoryImpl.java
Labels: ✨ Feature

#305 Fix: 공개글 리스트 조회 team entity에 대해 fetch join 적용
  src/main/java/com/codiary/backend/domain/post/repository/PostRepositoryImpl.java
Labels: 🎀 Fix

#303 Feat: 팀 설정을 위한 전체 팀 리스트 조회 API 기능 구현
  src/main/java/com/codiary/backend/domain/team/controller/TeamController.java
  src/main/java/com/codiary/backend/domain/team/converter/TeamConverter.java
  src/main/java/com/codiary/backend/domain/team/dto/response/TeamResponseDTO.java
  src/main/java/com/codiary/backend/domain/team/service/TeamService.java
Labels: ✨ Feature

#308 Fix: 최신순/인기순 게시물 조회 오류 수정
  src/main/java/com/codiary/backend/domain/post/repository/PostRepositoryImpl.java
Labels: 🎀 Fix, 🐞 BugFix

#310 Fix: 프로필 조회 수정
  src/main/java/com/codiary/backend/domain/member/controller/MemberController.java
Labels: 🎀 Fix

#299 Feat: 게시글 공동저자 설정 / 공개 범위 설정 / 소속 팀 설정 API 기능 구현
  src/main/java/com/codiary/backend/domain/coauthor/entity/Author.java
  src/main/java/com/codiary/backend/domain/post/controller/PostController.java
  src/main/java/com/codiary/backend/domain/post/dto/request/PostRequestDTO.java
  src/main/java/com/codiary/backend/domain/post/entity/Post.java
  src/main/java/com/codiary/backend/domain/post/service/PostCommandService.java
  src/main/java/com/codiary/backend/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ Feature

#317 Refactor: 마이페이지 쿼리 최적화 및 요청 사항 반영
  src/main/java/com/codiary/backend/domain/member/controller/MemberController.java
  src/main/java/com/codiary/backend/domain/member/dto/response/MemberResponseDTO.java
  src/main/java/com/codiary/backend/domain/member/repository/MemberRepository.java
  src/main/java/com/codiary/backend/domain/member/repository/MemberRepositoryCustom.java
  src/main/java/com/codiary/backend/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/com/codiary/backend/domain/member/service/FollowService.java
  src/main/java/com/codiary/backend/domain/member/service/MemberCommandService.java
  src/main/java/com/codiary/backend/domain/member/service/MemberQueryService.java
  src/main/java/com/codiary/backend/domain/techstack/repository/TechStackRepository.java
Labels: 🔨 Refactor
